services:
  - type: web
    name: f6-gimnasio
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        generateValue: true
